zigup.zig

This pr was originally just to add a new line to the help text so that it displays correctly on the terminal, but my editor also ran zig fmt. Feel free to remove the formatting if you don't like it.

add a new line to help text

---

zigup.zig

This fixes the variable, constant, and function argument names to be in accordance to the [documentation](https://ziglang.org/documentation/master/#toc-Names).

add better variable, constant, argument names

---

zigup.zig

Before deleting there should be a message, not after

---

README.md
test
zigup.zig

This adds:
- keep command
- unkeep command
- help messages for keep unkeep clean
- since std.fs.path.sep is a u8, it has to print it as a char

add keep and unkeep commands

---

build.zig

NOTE: this does not currently work because iguana does not compile on latest zig (inline functions got changed to calling convention inline). We should wait to merge this until it does.

iguana support in build.zig

---

zigup.zig

It was downloading linux-x86-64 on mac

Fix on macOS

---

test.zig
zigup.zig

Fix https://github.com/marler8997/zigup/issues/39

detect if zig path exe link is hidden by another program in PATH

---

.github/workflows/artifact.yml
build2.zig

Fix https://github.com/marler8997/zigup/issues/48

cross compile on CI

---

LICENSE

Fixes: https://github.com/marler8997/zigup/pull/73

add MIT-0 License

---

README.md

Sorry for the one-letter push, was just reading the README.

A small one-letter correction

---

test.zig
zigup.zig

fixes #93 
Thanks to @OlshaMB for helping me figure out how to reproduce this issue and root cause it.

handle when zig path link exists as a non-symlink entry

---

README.md

Now requires zig 0.12 not 0.11

---

build.zig

Compiling zigup for windows in Debug mode:
```
extracted archive in 12.00 s
extracted archive in 18.02 s
extracted archive in 14.56 s
```
Compiling zigup for windows in ReleaseSafe mode:
```
extracted archive in 3.28 s
extracted archive in 5.35 s
extracted archive in 4.36 s
```

build windows ci target in ReleaseSafe for faster zip extraction

---

build.zig

Build.zig now supports new path union syntax from https://github.com/ziglang/zig/pull/19597, and uses b.path() where appropriate

Updated build.zig to support new LazyPath syntax

---

.github/workflows/artifact.yml

something going wrong with macos...

switch from goto-bus-stop/setup-zig to mlugg/setup-zig

---

zigup.zig

Implements https://github.com/marler8997/zigup/issues/134
- Add flag to override the index to fetch the tarball link from.

add support for 3rd party index

---

build.zig
zigup.zig

- includes the --index option in the usage
- if we fail to parse the index content, print an error message

improvements to --index

---

build.zig
runtest.zig

I guess not having to copy all the compilers around for each test saved us quite a bit of time/space, around an order of magnitude for each.

fix CI running out of disk space

---

README.md

Thanks for the help and for the merging of #178.
I've realized that I forgot to update README.md, so this commit does juist that.

Update README with changed install directory behavior (XDG_DATA_HOME)

---

README.md

Considering adding this new section to the README

add anyzig to README
