zigup.zig
The standard library also had realpathAlloc which replaced another TODO.
=> remove TODO with merge of https://github.com/ziglang/zig/pull/7082

build.zig, zigup.zig
- use {s} specifier to print strings, replace warn with print
Related: marler8997/ziget#3
=> Fix format string deprecation, replace warn with print

.github/workflows/artifact.yml
Currently produces artifacts for linux and macos, windows is still borked. Should be easy enough to compile for other arches using zig and packaging them in the linux artifact
=> add artifact ci

test.zig, zigup.zig
It just removes the explicit check as missing of ``master`` symlink would already get detected by setDefaultCompiler().
Implements as per discussed on discord/issue topic.
I noticed that you aren't doing zig fmt, so I didn't did it either.
Closes #33
=> Implement ``zigup default master``

README.md, build2.zig, test.zig, win32exelink.zig, zigup.zig
On Windows, zigup currently uses a ".bat" file to set the default compiler and redirect any calls to the actual compiler executable.  This means than when invoking zig, it requires a shell and it breaks some programs from finding zig because they don't expect it to be `zig.bat`.  This Change replaces this batch file with a small executable instead so no shell is required and it uses the expected `.exe` extension.
Note that another solution to this would be to use the equivalent of posix's `execve` system call. I've started a userspace loader on windows to implement this https://github.com/marler8997/ldwin32
=> Use an "exelink" instead of a batch file on Windows

.github/workflows/artifact.yml, build2.zig, zigup.zig
While working on #44 I noticed that
1) ``zig build run -- --help``  is returning 1 while it should return 0 as its a successful execution of a command. After changing it, I found that,
2) Build.zig is not passing CLI arguments to zig build run in the first place :sweat_smile:
=> Return 0 code on help command and pass cli arguments to zig build run

README.md, test.zig, zigup.zig
Implements the command with the signature ``zigup run <version> <args>...`` or ``zigup run <version> -- <args>``
This PR implements the concept of positional arguments into zigup. This is because commands like ``zigup run 0.8.1 --help`` for example, would run --help command of zigup as opposed to zig 0.8.1, so the solution was to use positional arguments to reliably pass arguments into the compiler
Doesn't work for ``zigup run master``
Closes #23 
Open question:
1) ~~Should master be allowed? If so then same way as ``zigup default``?~~
2) ~~Is this way to pass args ok? The other solution is to pass all the arguments as a single string, that should be simple to implement, as per desired.~~
=> Implement command: zigup run

zigup.zig
Test on Allwinner D1 Nezha (RV64GCV)
Target: `riscv64-linux-musl`
CPU: `baseline_rv64`(GC) or `baseline_rv64+v` (GCV)
**Note:** LLVM & Zig does not recognize Xuantie(T-Head) CPU only sifive.
<details>
<summary>File Contents</summary>
```zig
const std = @import("std");
/// Zig version. When writing code that supports multiple versions of Zig, prefer
/// feature detection (i.e. with `@hasDecl` or `@hasField`) over version checks.
pub const zig_version = std.SemanticVersion.parse("0.9.1") catch unreachable;
/// Temporary until self-hosted is feature complete.
pub const zig_is_stage2 = false;
/// Temporary until self-hosted supports the `cpu.arch` value.
pub const stage2_arch: std.Target.Cpu.Arch = .riscv64;
/// Temporary until self-hosted can call `std.Target.x86.featureSetHas` at comptime. …
```
=> riscv64 added

.github/workflows/artifact.yml, build2.zig
closes #60 
This change introduces the ability to build aarch64 binaries and upload the artifacts. 
The CI can also be expanded to include other architectures. Sample run: [here](https://github.com/xEgoist/zigup/actions/runs/2914581904)
Because it's hard to test these builds on Github Action (with the exception of running linux builds under qemu), tests were left to the x86_64 builds.
=> Add CI build for aarch64 for all platforms

zigup.zig
Fixes an issue reported by user tech189 in issue #104.
=> gracefully handle PATH entires we don't have access to

.github/workflows/artifact.yml, .gitignore, test.zig, win32exelink.zig, zigup.zig
Simple rename of all the std.ChildProcess --> std.process.Child
=> Fixed compilation for zig 0.13

build.zig, zigup.zig
Extracted from #139.
The declarations `std.zig.CrossTarget`, `std.fs.MAX_PATH_BYTES`, and `std.mem.tokenize` were made into compile errors in zig version 0.13.0-dev.33+76fb2b685. Individually, these were deprecated (but not made compile errors) in:
- std.mem.tokenize: 0.10.0-dev.3139+9da3a9733
- std.zig.CrossTarget: 0.11.0-dev.1886+3179f58c4
- std.fs.MAX_PATH_BYTES: 0.11.0-dev.3382+cd62005f1
so this change makes zigup unbuildable with versions of zig prior to 0.11.0-dev.3382+cd62005f1 (if it was previously was), but allows building zigup with with zig versions after 0.13.0-dev.33+76fb2b685.
=> update for deprecated aliases in std

win32exelink.zig
This file was missed in the previous update (e37d205).
=> update win32exelink for deprecated std alias

index.html
I recently had to dust off a Windows machine and saw that zigup didn't have an equivalent PowerShell command. This PR adds a PowerShell command when Windows is selected. It also adjusts the UI so that this new item fits more gracefully.
New UI Adjustments:
Current UI:
=> feat(Website): PowerShell and Homebrew command and cosmetic adjustments for readability/sizing

README.md, build.zig
- Adds a `preferred_optimize_mode` to `zigup` binary;
- Adds a `strip = true` option to `zigup` binary;
These changes builds significantly smaller binary with no debug info (more suited to end users) when project is built with `zig build --release`.
note: this image is in text form on issue #169.
Fix GitHub Actions workflow to build and upload new files.
closes #169
=> set optimize mode and strip options

.github/workflows/artifact.yml, build.zig, build.zig.zon, zigup.zig, zip.zig
Updated Zig from 0.13.0 to 0.14.0 and addressed any breaking changes.
- [build.zig](build.zig): `std.Build.host` deprecated using `std.Build.Graph.host`. [[1]](https://ziglang.org/documentation/0.13.0/std/#std.Build:~:text=Deprecated.%20Use%20b.graph.host.)
- [build.zig.zon](build.zig.zon): `.fingerprint` introduced. [[2]](https://ziglang.org/download/0.14.0/release-notes.html#New-Package-Hash-Format)
- [zigup.zig](zigup.zig): `std.mem.page_size` was removed. [[3]](https://ziglang.org/download/0.14.0/release-notes.html#Runtime-Page-Size)
- [zip.zig](zip.zig): `std.builtin.Type` fields got renamed: [[4]](https://ziglang.org/download/0.14.0/release-notes.html#stdbuiltinType-Fields-Renamed)
- `Array` to `array`,
- `Struct` to `@"struct"`
- `Enum` to `@"enum"`
1. …
=> chore: upgrade Zig from 0.13.0 to 0.14.0

zigup.zig
Fixes #177.  Also related to discussion in #146.
Windows path is not changed because currently on Windows the path is derived from the location of the binary, so assuming Windows does not allow two identcal paths, the most logical path name, `zigup`, is not available.
I don't know about Windows conventions and don't have a Windows machine available to be able to test my assumptions.
=> Change default install path to $XDG_DATA_HOME/zigup on non-Windows systems

.github/workflows/artifact.yml, build.zig, zigup.zig
Added:
* ~`loongarch64-linux`~
* `x86-linux`
* `x86-windows`
Removed:
* `powerpc-linux`
=> Synchronize the list of supported targets with ziglang.org tarballs.

.github/workflows/artifact.yml, build.zig, zigup.zig
=> Add `s390x-linux` support.

zigup.zig
No CI builds for these yet as that depends on Zig 0.15.0.
=> Add handling for FreeBSD and NetBSD.
